package com.isufst.mdrrmosystem.response;

import java.util.List;

public record BudgetForecastResponse(
        int year,
        double totalForecast,
        String assumptions,
        List<BudgetForecastDriverResponse> drivers,
        List<BudgetForecastCategoryResponse> categories,

        // Historical actual budget values used by the chart
        List<ForecastChartPoint> actualSeries,

        // Next - year predictive forecast generated by BudgetForecastService.
        List<ForecastChartPoint> predictiveSeries
) {
}
